### ISSUE TITLE
Extraction Ratio Identical for All Samples

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#12]
It's too much of a coincidence not to be a bug.

![extratio](https://cloud.githubusercontent.com/assets/631218/23349242/7d80ce34-fd05-11e6-830f-843b08ce8434.png)

Also, only one of the samples has any mapping statistics shown.

I used version 1.10.

**Comment by jwinter6** [comment]
Hi Dario,
already fixed in 1.11, just forgot to push it for 1.10 release.
The same applies to the information Mapping to Reference.

Best
Jan
