### ISSUE TITLE
fileBegin error loading fastq.gz

### ISSUE THREAD

**Issue by cstubben** [boutroslab/CRISPRAnalyzeR#13]
I just ran `docker run --rm -p 80:3838 boutroslab/crispranalyzer:latest`  and tried to upload one fastq.gz file and it seems to load once, starts over and then returns ERROR: fileBegin called too many times.   Here's part of my fastq...

```
gunzip -c 13880X1.fastq.gz | head
@HWI-D00550:408:CAPWNANXX:7:1101:1156:2099 1:N:0:
TAAGTAGAGTCTTGTGGAAAGGACGAAACACCGATGCTGTCCAGCAACTN
+
CCCCCGGGGE>FEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
@HWI-D00550:408:CAPWNANXX:7:1101:1010:2100 1:N:0:
NAAGTAGAGTCTTGTGGAAAGGACGAAACACCGGCCCATCAGANTTCCGN
+
#3=AB=C1CFGGG>FGGGGGGGGGGGGGGGGGG@G/E/1=C:1#:0=EF#
@HWI-D00550:408:CAPWNANXX:7:1101:1123:2103 1:N:0:
TAAGTAGAGTCTTGTGGAAAGGACGAAACACCGGGGAAGTCCTCCAAATN

```

**Comment by jwinter6** [comment]
Hi,
thanks for this hint.
As far as I know this is a HTML5-based issue.
HTML5 is used for file uploading in chunks, and if there is something going wrong this might come up.
I will look for a work-around but it might be that is is not in my hands.

May I ask how large the fastq.gz file was?
Could you try it again please using the beta version via 
`
docker run --rm -p 80:3838 boutroslab/crispranalyzer:1.11BETA
`

Thanks for your help
Jan

**Comment by jwinter6** [comment]
closed due to inactivity, so I guess the issue is gone with the latest 1.11 release.
Will be reopened if required.
