### ISSUE TITLE
Bowtie2 Invalid Sensitivity Options

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#15]
The application offers `choices = list("very-sensitive-local", "local", "very-sensitive"))` for setting the Bowtie 2 sensitivity. However, `"very-sensitive"` is only applicable in end-to-end mapping mode whereas the `"very-sensitive-local"` is only valid for local alignment mode. According to Ben Langmead BenLangmead/bowtie2#66, the default end-to-end alignment of Bowtie 2 is not suitable if the read (e.g. 21 nucleotides) is longer than the reference sequence (e.g. 20 nucleotides). Bowtie 2 needs to be run with the `--local` option and in the Shiny application, `"very-sensitive"` is not a valid option for this kind of alignment so should be removed and replaced. Note that `"local"` is a mapping mode, not a sensitivity level, so it's also not a valid value for mapping sensitivity. For reference, valid sensitivity values are:

```
Preset options in --end-to-end mode
--very-fast         Same as: -D 5 -R 1 -N 0 -L 22 -i S,0,2.50
--fast              Same as: -D 10 -R 2 -N 0 -L 22 -i S,0,2.50
--sensitive         Same as: -D 15 -R 2 -L 22 -i S,1,1.15 (default in --end-to-end mode)
--very-sensitive    Same as: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50

Preset options in --local mode
--very-fast-local        Same as: -D 5 -R 1 -N 0 -L 25 -i S,1,2.00
--fast-local             Same as: -D 10 -R 2 -N 0 -L 22 -i S,1,1.75
--sensitive-local        Same as: -D 15 -R 2 -N 0 -L 20 -i S,1,0.75 (default in --local mode)
--very-sensitive-local   Same as: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50
```

This fix may moderately increase the mapping percentages.

**Comment by jwinter6** [comment]
Hi Dario,

in principle you are completely right.
But in the case of CRISPRAnalyzeR, the sgRNA barcode sequence will be extracted from the FASTQ file before mapping.
By this, the sgRNA barcode from the FASTQ file has the same length as the sgRNA reference in the library FASTA file - so an end-to-end alignment will be performed by default.

CRISPRAnalyzeR offers three modes:
- very-sensitive local
- local (which is `sensitive-local` as this is the local default setting for bowtie2)
- very-sensitive (which is end-to-end mode)

The `very-sensitive` mode is ok if the sgRNA barcode and the sgRNA reference are of the same length - which is the case by using the pre-defined settings of CRISPRAnalyzeR.

However, I will make this more clear in the next version and maybe only offer local options.
So far, I don't see 'huge' differences between any of the modes, with very-sensitive (end-to-end) and very-sensitive-local resulting in a similar mapping outcome.

Best
Jan

**Comment by DarioS** [comment]
Most of the extracted sequences will be 20 nucleotides, but doesn't the default pattern `ACC(.{20,21})G` also extract sequences that are 1 nucleotide longer than the reference sequence?

Oh, I didn't realise that the CRISPRAnalyzeR options are translated into Bowtie 2 format options rather then passed along as-is. Thanks for explaining that.
