### ISSUE TITLE
Upload max for local instance

### ISSUE THREAD

**Issue by jecorn** [boutroslab/CRISPRAnalyzeR#18]
First off, kudos on an amazing piece of work! The software is incredibly easy to use - perfect for some n my lab who aren't so computationally minded! And the docker container makes things a snap to set up!

One problem I've run in to. We're running the analyzer on a local machine using the docker container. And I get great results if I "upload" pre-made count tables. But I can't upload .fastq.gz files because I always get an error of "Maximum upload size exceeded". In this case each fastq.gz is between 1.5 GB and 4 GB. I can upload individual files, but not the larger ones. And in this case I need at least four uploads (prefereably eight), since there are two background replicates (4 GB each) and six samples (1.5-2 GB each).

Is there a way to disable the upload max for the local instance?

**Comment by jwinter6** [comment]
Hi,
thanks for this hint.
In the next update 1.14 I will include an additional parameter for docker to set the maximum upload size. By default, this is set to 4096 MB for a single file.

You can then adjust the size when starting CRISPRAnalyzeR:

```
docker run -e max_upload=8096 boutroslab/crispranalyzer::latest
```

Best
Jan

**Comment by jecorn** [comment]
Thanks for adding this feature. But as of 1.14.1, this isn't working. Starting the docker container I get stdout stating that the max upload size has been set. But whether I set max_upload to 8096 or even 20480, I still can't upload any files larger than 4 GB.

**Comment by jwinter6** [comment]
Hi Jacob,

I introduced a small typo in the dockerfile - is fixed now.
Please pull the latest version again with
`docker pull boutroslab/crispranalyzer:latest` .

Please let me know if it now works for you.
I also found a glitch with the proxy server that is also fixed now.

Thanks for pointing his out!

Best
Jan
