### ISSUE TITLE
CRISPRAnalyzeR web-service (crispr-analyzer.dkfz.de) keeps disconnecting

### ISSUE THREAD

**Issue by jwinter6** [boutroslab/CRISPRAnalyzeR#2]
Dear all,

just a quick note for all that experience random disconnects using our web-service at http://crispr-analyzer.dkfz.de.

Due to security enhancement, the CRISPRAnalyzeR web-service sometimes looses the streaming connection to your browser, which leads to a disconnection for data safety reasons.
**This ONLY occurs for our provided web-service and WILL NOT be the case for the local installation!**

We are working on that, but I cannot give any time estimation yet.

We recommend the installation using our provided Docker containers, which are available from the github repository or docker hub..

Please comment here if you have any questions regarding the disconnect issue.

Best
Jan

**Comment by jwinter6** [comment]
Dear all,

the connectivity issues should be solved.

Best
Jan

**Comment by 18792823** [comment]
Hi Jan,

Can you please provide me the access information of the Docker container you mentioned? I think I saw it somewhere but I can not find it anymore. If you can give me the link of the github repository or docker hub where the access information of the docker container was mentioned will also be fine. Thank you very much for your help.

Best
Mithun
