### ISSUE TITLE
Check Files Remains Disabled After Mapping

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#22]
After a successful mapping, the mapping statistics become available on the Review Your Data panel. If the mapping rate appears low, it would be convenient to be able to return to the Upload Your Data panel, change one of the Bowtie 2 settings and click on Check Files again. However, Check Files is disabled. Even uploading the FASTQ files again doesn't trigger the Check Files button to reactivate. The application has to be restarted and all uploaded files and user-modified settings are lost.

**Comment by jwinter6** [comment]
Hi,

Have you tried to click the Change Files button next to it?
This will reset the mapping and allows you to click check files again.

Best
Jan

Am 12. April 2017 09:00:45 schrieb DarioS <notifications@github.com>:

After a successful mapping, the mapping statistics become available on the Review Your Data panel. If the mapping rate appears low, it would be convenient to be able to return to the Upload Your Data panel, change one of the Bowtie 2 settings and click on Check Files again. However, Check Files is disabled. Even uploading the FASTQ files again doesn't trigger the Check Files button to reactivate. The application has to be restarted and all uploaded files and user-modified settings are lost.

-

**Comment by DarioS** [comment]
It works. But needing to click on Use Other Files when only the Bowtie 2 options were changed is not intuitive, since no input files were changed.
