### ISSUE TITLE
Custom Regular Expression Causes Extraction Failure

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#23]
I used the regular expression `ACC(.{20,21})GTTTT` and received the error "The entered FASTQ regular expression did only work for 0 to 0% of sequences within your FASTQ files." Using  `grep` directly demonstrates that the regular expression I tried to use is correct:

    $ zgrep -E 'ACC(.{20,21})GTTTT' treatedA.fastq.gz | head -n 3 -
    ATACACGATCTCTTGTGGAAAGGACGAAACACCGAGTATCTAATTATAGCCTTCGTTTTAGAGCTAGAAATAGCA
    ATCGATTCCTTGGTTCTTGTGGAAAGGACGAAACACCAGCGCCGACGTGCTCACAGTGGTTTTAGAGCTAGAAAT
    ATACACGATCTCTTGTGGAAAGGACGAAACACCGCAGATGGGCGGACAATTTCAGTTTTAGAGCTAGAAATAGCA

Choosing Standard for LenticrispV2 fails with "The entered FASTQ regular expression did only work for 1.1 to 1.64% of sequences within your FASTQ files." although it doesn't fail if I use it in a new application session without having entered a custom error-raising regular expression first. The only way to continue analysis is to restart the application and choose LenticrispV2 the first time. The extraction rate is then about 96%.

**Comment by jwinter6** [comment]
Hi,

just to make it clear:
- it works if you select the default setting in the beginning
- once you add a custom regular expression (the one above), it fails (though it is the same regex)
- and if you then select one of the defaults afterwards, it does not work anymore?

One question:
- did you click the reset button between in between?

Seems like there is a glitch in the reactive handling - thanks for pointing this out.
However I did not observe any issues with custom regular expressions before, but I will also check this.

Best
Jan

**Comment by DarioS** [comment]
That summary describes the problem concisely.

I didn't click on the User Other Files button.

**Comment by jwinter6** [comment]
Hi,
I am on it and it will be changed with the 1.16 release in a couple of days.

Best
Jan
