### ISSUE TITLE
low % alignment terminates analysis

### ISSUE THREAD

**Issue by nvanduse** [boutroslab/CRISPRAnalyzeR#25]
When I upload several libraries if the alignment is below ~30% for any one of them, a warning message pops up and the analysis is terminated. Is there anyway to proceed with the analysis even with low % alignment?
thanks
Nathan
![image](https://cloud.githubusercontent.com/assets/27821010/25240283/6b7ba5a4-25c0-11e7-9009-71c6dbf75c10.png)

**Comment by jwinter6** [comment]
Hi Nathan,

thanks for your post.
Right now, there is no way to proceed except for leaving those files out.
The idea was to raise the awareness of such issues instead of just going on.
I will add a checkbox that can be activated to proceed though the alignment rate is that low.

Best
Jan

**Comment by nvanduse** [comment]
Sounds good! Thanks

**Comment by jwinter6** [comment]
Hi Nathan,

I will upload a 1.16BETA version later this day (still testing).
Could you please give it a try and let me know if it works?
It also harbors the new FASTQ handling pipeline that is 14x faster.

you can just get it using
`
docker pull boutroslab/crispranalyzer:1.16BETA
`

and when you start the docker, just replace 
`
boutroslab/crispranalyzer:latest
`
with
`
boutroslab/crispranalyzer:1.16BETA
`

In Case you use Kitematic, you can just change the version by choosing a different tag.

Best
Jan

**Comment by nvanduse** [comment]
Sure, thanks.

**Comment by jwinter6** [comment]
Hi Nathan,

the BETA version is up and running.

Best
Jan
