### ISSUE TITLE
Brie Library Fasta "repeated guides"

### ISSUE THREAD

**Issue by Kevbot8000** [boutroslab/CRISPRAnalyzeR#28]
Hi,

I have tried to analyze my CRISPR data a few times using CRISPR Anlyzer version 1.14, 1.17 and 1.2 but all of these versions say that the uploaded Brie FASTA file has a duplicate sgRNA identifier in the sgRNA library file. Is there an issue with the brie library fasta file that was used in version 1.2? Is this the same file that was uploaded in the GitHub page? The program looks extremely user friendly and promising- I am hopeful there is a simple fix! 

Thanks!

**Comment by jwinter6** [comment]
Hi,

thanks for your comment.
Did you use the preset FASTA file (Version 1.20 and higher) or the one downloaded from this repository?
As I do not have Brie Sequencing Data on hands, I can just try the FASTA file that I provide within this repository, and for this one there is no message about repeated guides.

Please give the following FASTA file a try:

https://github.com/boutroslab/CRISPRAnalyzeR/blob/master/fasta/FASTA_Brie.fasta

In case you use CRISPRAnalyzeR 1.20 and higher, you can directly select the Brie preset or alternatively use the CUSTOM setting and upload the above linked FASTA file.

Please give it a try and post a screenshot in case the error message appears again. Please also send me a screenshot about the setting on the Upload Data page.
If you want to keep this information private, please send me an email to jan.winter@dkfz-heidelberg.de.

Thanks for your help :)

Best,
Jan

**Comment by jwinter6** [comment]
Just for followup for others (via email):

Ok so I found the issue, this is something related to having majority of zeroes and failing to perform DESeq2-based normalization.
I will fix the confusing error message to the correct one, sorry for this.


Best
Jan
