### ISSUE TITLE
crash while creating FASTQ quality report

### ISSUE THREAD

**Issue by amayer21** [boutroslab/CRISPRAnalyzeR#29]
Hello,
Thank you for developing this tool to analyse CRISPR screens!!! I've been analysing a preliminary experiment and found it very easy to use and so powerful. However I noticed that it often crash while creating the FASTQ quality report (when starting from fastq.gz files). It stays at 91% for ever and the only way to get out is to reload the page and upload the data again. Therefore I was wondering if it would be possible to choose not to generate this report. I already have all the information about my read quality from Illumina BaseSpace, so I don't need them to be computed again. 
I have only very basic programming knowledge, so I don't know how much work it would be to make that step optional, but I think it would really help.
Thank you very much,
All the best,
Alice

**Comment by jwinter6** [comment]
Hi Alice,

thanks for your comment - positive words are always welcome :)
The FASTQ quality report takes some time to be generated, but in this case the issue might be something different.

I will implement a switch to turn off FASTQ quality report generation in the next big update.

To track down why it hangs at 92% for you, please tell me:
- are you using the online version hosted @ crispr-analyzer.org ?
- in case you use the online web version, please go to the help and send me a ticket -> this allows me to track the logs what might have gone wrong.

- if you use the local docker installation, which version do you use?
- if you use the local version, please go to About CRISPRAnalyzeR within the app and click on the Download Log Files button and email me the zip file to jan.winter@dkfz-heidelberg.de

Thanks a lot for you help.

Best
Jan

**Comment by DarioS** [comment]
I think the last step takes much longer than the earlier steps. Note that the progress bar percentages aren't designed to increment by equal times.

**Comment by jwinter6** [comment]
Switch added for the next release
