### ISSUE TITLE
CRISPRAnalyzeR container crashing during "Check Upload" step

### ISSUE THREAD

**Issue by deb-m** [boutroslab/CRISPRAnalyzeR#30]
When I am trying to test run the example data in my local installation the container is crashing asking me to reload the page. Here are my settings:-

> \# docker info
> Containers: 2
>  Running: 1
>  Paused: 0
>  Stopped: 1
> Images: 3
> Server Version: 17.09.0-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
> runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
> init version: 949e6fa
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.4.0-96-generic
> Operating System: Ubuntu 16.04.3 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 12
> Total Memory: 31.32GiB
> Name: pje-lab
> ID: JB3H:RF62:6HWZ:YIXL:4TGF:2U6V:PSFD:DJFS:TGYI:DGKL:WVWP:A7TZ
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support

The docker logs:-

>\# docker logs 6f77558...
> [CUSTOM] setting enhanced websocket settings
> [CUSTOM] setting verbose shiny server and application logfiles
> [CUSTOM] setting the path to the COSMIC database
> [CUSTOM] EnrichR interface
> [CUSTOM] setting the EnrichR URL
> [CUSTOM] Set maximum upload Size
> [CUSTOM] setting number of threads for Bowtie2

Any help regarding the settings or how to debug will be greatly appreciated.
Thanks

**Comment by jwinter6** [comment]
Hi,

thanks for your comment.

Could you please tell me the following:

- which version do you use?

In case you are at the latest, could you please go to the About CRISPRAnalyzR page and send me a screenshot and the log files (Download logfiles button) to jan.winter@dkfz-heidelberg.de?

Best, Jan

**Comment by deb-m** [comment]
Hi Jan,
I am using latest (# docker run --rm -e bowtie_threads=2 -p 80:3838 boutroslab/crispranalyzer:latest)

I tried to reproduce the error today, and it went through without any error. I did restart the machine in between, do not know if that helped. 

Thanks for your reply.
Deb

**Comment by deb-m** [comment]
Hi Jan, 
After testing that the example data is uploading properly and being checked, I went ahead with 5 fastq.gz files of my experiment, and the server crashed again. 

1. I am using latest (# docker run --rm -e bowtie_threads=2 -p 80:3838 boutroslab/crispranalyzer:latest).

2. I am sending the zipped logfile to your email address.

Thanks
Deb

**Comment by jwinter6** [comment]
HI Deb,

just checked the logs and it seems to be the FASTA Brunello file in the default settings which I forgot to include in the docker image.

Did the Example data work now? (so not Brunello but Example)?
In the logs you sent I cannot find any crash when you used the sample data.
Can you do me a favor and give it another try with the sample data?
Once it crashed, close the browser, open it again and then please send me the log files from the About CRISPRAnalyzeR page.

Thanks for you help, I really appreciate it.
Jan

**Comment by deb-m** [comment]
Hi Jan,


> On Oct 4, 2017, at 12:17 PM, Jan Winter <notifications@github.com> wrote:
> 
> HI Deb,
> 
> just checked the logs and it seems to be the FASTA Brunello file in the default settings which I forgot to include in the docker image.
> 
Related to this I find two names for the Brunello sgRNA library at GitHub:-
1. At master, under the fasta dir, there is a file named “FASTA_Brunello.fasta”
2. In README.md, under the section, "Premade sgRNA library fasta files (image), there is a “FASTA” link in the "Brunello” row, which when I click I am getting a 404 Error as it is searching for a file named “FASTA_brunello_library.fasta”. 



> Did the Example data work now? (so not Brunello but Example)?
> 
The example data with example sgRNA lib is working without problem. 
> In the logs you sent I cannot find any crash when you used the sample data.
> 
Please disregard the logs that I sent you earlier, as it is not related to the sample data crash.
> Can you do me a favor and give it another try with the sample data?
> 
Sure.
> Once it crashed, close the browser, open it again and then please send me the log files from the About CRISPRAnalyzeR page.
> 
I was not able to reproduce the crash. However as per your instruction,  I have attached the log after the data upload was successful (CRISPRAnalyzeR_17-10-04_15-30-46_logs.zip) as well as the success screenshots (Sample_data_success_screenshots.pdf). 
> Thanks for you help, I really appreciate it.
> 
Thank you! and Boutros Lab for developing such an user friendly analysis interface.
> Jan
> 

Now let me explain the 2nd issue. 
1. I downloaded the "FASTA_Brunello.fasta" from "master/fasta”.
2. In CAnalyzeR I passed on this downloaded FASTA_Brunello.fasta as a CUSTOM sgRNA library file.
3. I uploaded 5 fastq.gz sequencing data files of my experiment.
4. Clicked “Upload and Check files” button 
5. The data was uploaded and checked successfully.
6. I downloaded the Readcount.zip and Sequencing_quality.html files in the next page.
7. In the next page I setup five groups and added the readcount files to the groups.
8. Next at the setup analysis page, I kept everything at default settings, chose gr2 vs gr5 and clicked “Start Analysis”.

The analysis did not proceed, as it complained about duplicate sgRNA identifier, please see screenshot file (Screenshot at 2017-10-04_15-45-06.png)

After this happened, I issued the following command to identify any duplicate lines.

<code>$ wc -l FASTA_Brunello.fasta<\code>
  154882 FASTA_Brunello.fasta

<code>$ uniq FASTA_Brunello.fasta | wc -l<\code>
  154882

<code>$ awk '!a[$0]++' FASTA_Brunello.fasta | wc -l<\code>
  154882

<code>$ awk 'a[$0]++' FASTA_Brunello.fasta | wc -l<\code>
       0

Seems like all lines in the FASTA_Brunello.fasta are unique. 

Then what is the problem during analysis? I have attached the log file of this particular issue, please see (CRISPRAnalyzeR_17-10-04_15-46-01_logs.zip).

Any advice, will be very helpful.

Thanks
Deb

**Comment by jwinter6** [comment]
Hi Deb,

the different FASTA files will be gone once I update the latest version in the next days.

I will check the log what exactly is the issue, but it seems this is a coding mistake, which will be fixed in the next version.

cheers
Jan
