### ISSUE TITLE
Error while using the "FASTA_Brunello.fasta" file during analysis 

### ISSUE THREAD

**Issue by deb-m** [boutroslab/CRISPRAnalyzeR#31]
The server was crashing during the "check upload" stage, when I was choosing the "Brunello" button. To circumvent this issue I chose "Custom" and provided the "FASTA_Brunello.fasta" file which I downloaded from the Github page (https://github.com/boutroslab/CRISPRAnalyzeR: fasta/FASTA_Brunello.fasta).

After manually providing this file the "Check Upload" went through and I received the Readcount and the Sequencing quality files.

Next when I setup the analysis, I received the following error message:-

> It looks like you have duplicate sgRNA identifier in your sgRNA library file.
> Please make sure only unique sgRNA identifier are present in your sgRNA fasta library file.For further assistence please briefly describe your problem by sending us a ticket or posting it to the forum.

I have saved the CRISPRAnalyzeR log file at this point- and can share it if required.

Thanks
Deb

**Comment by jwinter6** [comment]
Hi Deb,

thanks for your logs regarding issue 30 #30 .
I just checked them and actually it is the FASTA Brunello file, When I build the docker image I forgot to put the FASTA file in the right place.

There will be a new major release this weekend, where this is fixed.

Thanks for your help and Best,
Jan
