### ISSUE TITLE
CRISPRAnalyzeR crashed for the sample data

### ISSUE THREAD

**Issue by xuguorong2016** [boutroslab/CRISPRAnalyzeR#37]
Hi Jan,

I installed CRISPRAnalyzeR with docker on my local mac laptop without problem. But I got the crash issue when I tried to load the TRAIL_Resistance sample data. 
<img width="1200" alt="screen shot 2018-01-19 at 11 25 26 pm" src="https://user-images.githubusercontent.com/19210374/35181092-5b679442-fd70-11e7-9ec5-9f3404dac292.png">

Then I access the demo website and got the same issue.
http://crispr-analyzer.dkfz.de/

From the log files, I did not find any problem. Do you have any ideas?
[logs.zip](https://github.com/boutroslab/CRISPRAnalyzeR/files/1648637/logs.zip)

Your response would be really appreciated!

Guorong

**Comment by jwinter6** [comment]
Hi Guorong,
thanks for your help :)
If the app greys out it lost the connection to your browser.
This can also be an issue with the app, that is true.
I just tried the sample data using the online demonstration and it worked for me.

I selected EXAMPLE Trail resistance in the library selection and uploaded the following files:
![image](https://user-images.githubusercontent.com/7203572/35182389-2a7a388a-fdd4-11e7-8bba-035601ef0c43.png)

can you please give it another try?

I also checked your logs and there might be a small issue when the shiny session is initiated, I will have a look into it.

Best
Jan

**Comment by xuguorong2016** [comment]
Hi Jan,

Thanks a lot!
I just selected the pre-made screen library EXAMPLE Trail resistance and it worked well. But I downloaded the fasta file from the website to load back, it greyed out. I think it is possible the fasta file issue. I have attached the fasta file and please try it.

Thanks,
Guorong
[pilotscreen_TRAIL.fasta.zip](https://github.com/boutroslab/CRISPRAnalyzeR/files/1648943/pilotscreen_TRAIL.fasta.zip)

**Comment by xuguorong2016** [comment]
Hi Jan,

I think I figured out what's going on. When I loaded the downloaded fasta file into CRISPRAnalyzeR I did not check the type of screen library. So the CRISPRAnalyzeR got the crash issue. After I selected the custom option and then uploaded the fasta file, it works fine.

Thanks,
Guorong

**Comment by jwinter6** [comment]
Glad it works now :)

best,
Jan
