### ISSUE TITLE
the link to the toolbox is wrong

### ISSUE THREAD

**Issue by frymor** [boutroslab/CRISPRAnalyzeR#40]
Hi,
I think they have changed the links, but the link to the toolbox doesn't point to the right tool. 
can you fix it?

thanks
Assa

**Comment by jwinter6** [comment]
Hi Assa,

could you please tell me where the links are incorrect?

Best
Jan

**Comment by frymor** [comment]
Hi,
in the User-Interface based installation (recommended) on macOS and Windows.
In nr. 4 **Download the Docker Toolbox from the docker website**
here is a link to the toolbox, but it points to https://www.docker.com/get-docker

**Comment by jwinter6** [comment]
thanks is going to be fixed
