### ISSUE TITLE
CRISPRAnalyzeR vs. caRpools

### ISSUE THREAD

**Issue by frymor** [boutroslab/CRISPRAnalyzeR#41]
I was wondering what the differences between the two packages. 
I would like to install the workflow on an Ubuntu server, but for personal use and not for multiple users.

I couldn't find out how to do so for the CRISPRAnalyzeR. Are there instructions somewhere?

Thanks again
Assa

**Comment by jwinter6** [comment]
Hi Assa,

CRISPRAnalzyeR comes as-it-is in a docker container and cannot be used as a script version. It is not even an R package, caRpools is an R package and can only be used as a script.
You can run it on any machine supported by docker and experience the interactive analysis.

you can find some basic help for the installation here:
https://github.com/boutroslab/CRISPRAnalyzeR/blob/master/README.md

The usage is highlighted in youtube tutorials, but you can also try our online demonstration first available at http://www.crispr-analyzer.org.

I will come back to you in the issue #42 also with some command line based instructions in the next days.

best
Jan
