### ISSUE TITLE
Unable to load data - disconnected from server

### ISSUE THREAD

**Issue by jacboero** [boutroslab/CRISPRAnalyzeR#45]
Hey! 

I finally got my data and wanted to test CRISPRAnalyzer, but I don't seem to be able to load my data into the suite (neither online nor if I run it on my own computer). While check of the uploaded files, the error "discconected from server" appears and i have to reload. I saw that other ppl had the same issue and could solve it, by deactivating the fast extraction mode, however that didn't help. Any other suggestions I could try?

Thanks!
Jacob

**Comment by MerRome** [comment]
Hi Jacob,
I just started to use CRISPRAnalyzer as well and had the same problem.
Did you remember to specifically select "custom library" in step 1? This mistake was also described earlier and for me fixed it.
Best,
Merrit

**Comment by jwinter6** [comment]
HI Jacob,

sorry for the late reply.
Could you please send me some logs?
Try it again and after it stalled go to about CRISPRAnalyzer and then Download logs.

Best,
Jan

**Comment by jwinter6** [comment]
I assume the issue is not required anymore.
