### ISSUE TITLE
link to pre-made sgRNA FASTA file from Brunello library is not working

### ISSUE THREAD

**Issue by JoseEspinosa** [boutroslab/CRISPRAnalyzeR#47]
Hi,

I was trying to download the FASTA file containing the sgRNA from thew Brunello library from your wiki:

`/wiki/Data-Upload:-Pre-Made-sgRNA-Library-files-for-common-CRISPR-libraries`

But the link to this FASTA file is not working.

Thanks a lot,

j

**Comment by JoseEspinosa** [comment]
In case someone is interested the FASTA file can be also found in the repo [here](https://github.com/boutroslab/CRISPRAnalyzeR/blob/master/fasta/FASTA_Brunello.fasta)

**Comment by jwinter6** [comment]
Hi, the FASTA file is already included in the pre-defined settings, so no need to download it separately anymore.
Alternatively it is located, as you pointed out, in the fasta subfolder.

Cheers,
Jan
