### ISSUE TITLE
Empirical CDF Plot

### ISSUE THREAD

**Issue by DarioS** [boutroslab/CRISPRAnalyzeR#6]
I'm collaborating with a biologist, and he likes QC plots like those in [Genome-Scale CRISPR-Cas9 Knockout Screening in Human Cells](http://science.sciencemag.org/content/343/6166/84). Figure 2 parts B and C are cumulative distribution plots. Could two radio buttons be added to the Distribution plot's tab; one for PDF and one for CDF - to allow the user to switch the display between them.

**Comment by jwinter6** [comment]
Hi Dario,
thanks for your feature request,I put this on my todo list and let you know once this is done.
After I fixed the glitches you mentioned in the other issues I will implement these two plots.

Best
Jan

**Comment by jwinter6** [comment]
added in version 1.11
