### ISSUE TITLE
 CRISPRAnalyzeR website down

### ISSUE THREAD

**Issue by sarah-sarah** [boutroslab/CRISPRAnalyzeR#60]
Hi

The CRISPRAnalyzeR homepage has a 'Service Temporarily Unavailable' message. Any idea when it's going to be fixed?

Thanks! 
Sarah 
:)

**Comment by jwinter6** [comment]
Hi Sarah,

as I am not working for the DKFZ anymore I don't have direct access to the
server.
However I contacted the responsible people and I am quite sure it will be
back up again soon.
Sorry for the trouble, please let me know how it is going.

Best,
Jan

Am Do., 30. Jan. 2020 um 23:11 Uhr schrieb sarah-alexandrou <
notifications@github.com>:

**Comment by jwinter6** [comment]
It is currently down again but will be back up soon.
